### ISSUE TITLE
nginx support

### ISSUE THREAD

**Issue by murilobd** [demystifying-dev/strapi-docker-compose-example#1]
Hi!
Thanks for this repo and article! Really good!!
Could you also add nginx to docker-compose and show us how it would looks like?

Thanks!

**Comment by traderpedroso** [comment]
> Hi!
> Thanks for this repo and article! Really good!!
> Could you also add nginx to docker-compose and show us how it would looks like?
> 
> Thanks!

best way to use Nginx on docker is using Nginx Proxy Manager is a open source and have docker-compose ready
repo https://github.com/jc21/nginx-proxy-manager


```yml
version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  db:
    image: 'jc21/mariadb-aria:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./data/mysql:/var/lib/mysql
 ```
